//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#ifndef NANO_TUYALINK_BOOTLOADER_H
#define NANO_TUYALINK_BOOTLOADER_H

#include <nanoCLR_Interop.h>
#include <nanoCLR_Runtime.h>
#include <nanoPackStruct.h>

struct Library_nano_TuyaLink_Bootloader_nano_TuyaLink_Bootloader_TuyaBootloader
{
    NANOCLR_NATIVE_DECLARE(Update___VOID);
    NANOCLR_NATIVE_DECLARE(EnterProprietaryBooter___STATIC__STRING);

    //--//
};

struct Library_nano_TuyaLink_Bootloader_System_Runtime_CompilerServices_RefSafetyRulesAttribute
{
    static const int FIELD__Version = 1;

    //--//
};

extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nano_TuyaLink_Bootloader_Native;

#endif // NANO_TUYALINK_BOOTLOADER_H
