//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "nano_TuyaLink_Bootloader.h"
#include "nano_TuyaLink_Bootloader_nano_TuyaLink_Bootloader_TuyaBootloader.h"

using namespace nano_TuyaLink_Bootloader_Native::nano_TuyaLink_Bootloader;


HRESULT Library_nano_TuyaLink_Bootloader_nano_TuyaLink_Bootloader_TuyaBootloader::Update___VOID( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        TuyaBootloader::Update(  hr );
        NANOCLR_CHECK_HRESULT( hr );

    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_nano_TuyaLink_Bootloader_nano_TuyaLink_Bootloader_TuyaBootloader::EnterProprietaryBooter___STATIC__STRING( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        const char* retValue = TuyaBootloader::EnterProprietaryBooter(  hr );
        NANOCLR_CHECK_HRESULT( hr );
        SetResult_LPCSTR( stack, retValue );
    }
    NANOCLR_NOCLEANUP();
}
