//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "nano_TuyaLink_Bootloader.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    Library_nano_TuyaLink_Bootloader_nano_TuyaLink_Bootloader_TuyaBootloader::Update___VOID,
    NULL,
    NULL,
    Library_nano_TuyaLink_Bootloader_nano_TuyaLink_Bootloader_TuyaBootloader::EnterProprietaryBooter___STATIC__STRING,
    NULL,
    NULL,
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nano_TuyaLink_Bootloader_Native =
{
    "nano.TuyaLink.Bootloader",
    0xD015CCEF,
    method_lookup,
    { 1, 0, 0, 0 }
};

// clang-format on
